CREATE TABLE IF NOT EXISTS courses (
    id SERIAL PRIMARY KEY,
    unique_code VARCHAR(20) NOT NULL UNIQUE, 
    name VARCHAR(100) NOT NULL,
    description TEXT, 
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);